import { randomInt } from 'node:crypto';

/**
 * Generating the OTP code itself (Step 12).
 *
 * Only generation is left here: hashing and comparison moved to
 * `src/identity/credentials/secret-hash.ts` in Step 34a, when the transaction PIN became
 * a second caller of the same two operations. Generation stayed because it is the one
 * part that is about a *code* - a fixed number of digits, drawn from a CSPRNG and
 * zero-padded - and neither a PIN nor a password is generated by the API.
 */

/**
 * Generates a numeric code of `length` digits.
 *
 * `randomInt` (CSPRNG) rather than `Math.random`, which is seeded predictably
 * enough that guessing the next code would be an attack on the generator instead
 * of on the 6 digits.
 *
 * The padding is load-bearing: a code of `012345` has to arrive as six digits, or
 * a user typing what the SMS says is told their code is wrong.
 */
export function generateOtpCode(length: number): string {
  return randomInt(0, 10 ** length)
    .toString()
    .padStart(length, '0');
}
